apiVersion: v1
kind: Pod
metadata:
  name: muj02
  labels:
    app: muj02
spec:
  restartPolicy: OnFailure
  containers:
  - name: muj-container
    image: alpine
    command:
    - /bin/sh
    - -c
    - |
      sleep 60
      echo "je to nejake rozbite"
      exit 1
