apiVersion: v1
kind: Pod
metadata:
  name: muj04
  labels:
    app: muj04
spec:
  nodeSelector:
    tenhle: neexistuje
  restartPolicy: OnFailure
  containers:
  - name: muj-container
    image: alpine
    command:
    - /bin/sh
    - -c
    - |
      sleep infinity
