apiVersion: v1
kind: Pod
metadata:
  name: muj06
  labels:
    app: muj06
spec:
  restartPolicy: OnFailure
  containers:
  - name: muj-container
    image: python:rc-alpine3.13
    command:
    - python
    - -c
    - |
      import time

      print("start!")
      time.sleep(10)
      bytearray(512000000)
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 100m
        memory: 100Mi