apiVersion: v1
kind: Pod
metadata:
  name: hello
  labels:
    app: hello
spec:
  containers:
    - name: hello
      image: 123456789123.dkr.ecr.eu-west-1.amazonaws.com/mujobraz04:mujtag
      ports:
        - name: http
          containerPort: 8080
          protocol: TCP

